monju_project/bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.detail, name='detail'),
    path('new', views.new, name='new'), # 投稿用WebページのURL
    path('create', views.create, name='create'), # 新規投稿をデータベースに保存するためのURL
]

monju_project/monju_app/urls.py
from django.urls import path
  
from . import views
  
urlpatterns = [
    path('', views.index, name='index'),
]

monju_project/monju_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView # インポート

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('hello/', include('hello.urls')),
    path('bbs/', include('bbs.urls')),
    path('', RedirectView.as_view(url='/bbs/')), # トップページにアクセスすると/bbs/にリダイレクト
]

monju_project/bbs/models.py
from django.db import models

class Article(models.Model):
    content = models.CharField(max_length=140)
    user_name = models.CharField(max_length=50, null = True) # nameカラムを追加

    def __str__(self):
        return self.content

monju_project/monju_app/models.py
from django.db import models

# Create your models here.

monju_project/bbs/forms.py
from django import forms
from .models import Article # models.pyからArticleクラスをインポート

# SearchFormクラスを定義
class SearchForm(forms.Form):
        keyword = forms.CharField(label='', max_length=50)

# 新規投稿フォームを定義
class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('content', 'user_name')

monju_project/bbs/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Article
from .forms import SearchForm
from .forms import ArticleForm # forms.pyからArticleFormクラスをインポート

def index(request):
    searchForm = SearchForm(request.GET)
    if searchForm.is_valid():
        keyword = searchForm.cleaned_data['keyword']
        articles = Article.objects.filter(content__contains=keyword)
    else:
        searchForm = SearchForm()
        articles = Article.objects.all()

    context = {
    'articles': articles,
    'searchForm': searchForm,
    }
    return render(request, 'bbs/index.html', context)

def detail(request, id):
    article = get_object_or_404(Article, pk=id)
    context = {
        'article': article,
    }
    return render(request, 'bbs/detail.html', context)

# 新規投稿画面のWebページを返すnew関数
def new(request):
    articleForm = ArticleForm() # ArticleFormオブジェクトを生成
    # テンプレート側でarticleFormのデータを取り出せるようにcontextに渡す
    context = {
        'articleForm': articleForm,
    }
    return render(request, 'bbs/new.html', context) # new.htmlというテンプレートを返す

#新規投稿データを保存するcreate関数
def create(request):
    # リクエストのメソッドがPOSTなら
    if request.method == 'POST':
        articleForm = ArticleForm(request.POST) # リクエストから取り出したデータを代入
        # 受け取ったデータが正常なら
        if articleForm.is_valid():
            article = articleForm.save() # データを保存
    context = {
        'article': article,
    }
    return render(request, 'bbs/posted.html', context) # detail.htmlを返す

    # 投稿編集ページを返すedit関数
def edit(request, id):
    article = get_object_or_404(Article, pk=id) # 指定した投稿をarticle変数に代入
    articleForm = ArticleForm(instance=article) # ArticleFormクラスからarticleFormオブジェクトを生成
    context = {
        'article': article,
        'articleForm': articleForm,
    }
    return render(request, 'bbs/edit.html', context) # edit.htmlというテンプレートを返す

# 編集データを保存して個別投稿ページを返すupdate関数
def update(request, id):
    # リクエストのメソッドがPOSTなら
    if request.method == 'POST':
        article = get_object_or_404(Article, pk=id)
        articleForm = ArticleForm(request.POST, instance=article) # ArticleFormクラスからarticleFormオブジェクトを生成
        # 受け取ったデータが正常なら
        if articleForm.is_valid():
            articleForm.save() # データを保存
    context = {
        'article': article,
    }
    return render(request, 'bbs/detail.html', context) # detail.htmlを返す

# 投稿データを削除するdelete関数
def delete(request, id):
    article = get_object_or_404(Article, pk=id) # 指定した投稿をarticle変数に代入
    article.delete()

    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'bbs/index.html', context) # index.htmlを返す

monju_project/monju_app/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world!")

monju_project/templates/bbs/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
    <meta charset="utf-8">
      <title>Djangoを使ってみよう！</title>
      <style>h1 {color: #0000ff}</style>
    </head>
    <body>
      {% block content %}
      {% endblock %}
    </body>
</html>

monju_project/templates/bbs/detail.html
{% extends "./base.html" %}

{% block content %}
    <h1>{{ article.id }}の個別投稿ページ</h1>
    <p>{{ article.content }}, {{article.user_name }}</p>
    <div>
      <button onclick='location.href="{% url "bbs:index" %}"'>一覧</button>
      <button onclick='location.href="{% url "bbs:edit" article.id %}"'>編集</button>
      <button onclick='location.href="{% url "bbs:delete" article.id %}"'>削除</button>
    </div>
{% endblock %}

monju_project/templates/bbs/edit.html
{% extends "./base.html" %}
 
{% block content %}
  <h1>Djangoで作る新規投稿フォーム</h1>
 
  <form action='{% url "bbs:update" articel.id %}' method="post">
    {% csrf_token %}<!-- セキュリティのための記述 -->
    {{ articleForm }}<!-- views.pyから受け取ったarticleFormを表示 -->
    <button type='submit'>保存</button>
    <a href='{% url "bbs:detail" article.id %}'>個別投稿ページへ戻る</a>
  </form>
{% endblock %}

monju_project/templates/bbs/index.html
{% extends "./base.html" %}

{% block content %}
  <h1>Djangoで作る1行掲示板</h1>

  {% if searchForm %}
    <form action='{% url "bbs:index" %}' method="get">
      <div>
        {{ searchForm }}
        <input type="submit" value="検索">
        <a href='{% url "bbs:index" %}'>クリア</a>
      </div>
    </form>
  {% endif %}

  {% for article in articles %}
    <p>
      <a href='{% url "bbs:detail" article.id %}'>{{ article.content }}</a>
      {{ article.user_name }}
    </p>
  {% endfor %}

  <!-- 新規投稿ページへの遷移ボタン -->
  <p>
    <button onclick='location.href="{% url "bbs:new" %}"'>新規投稿</button>
  </p>

{% endblock %}

monju_project/templates/bbs/new.html
{% extends "./base.html" %}

{% block content %}
  <h1>Djangoで作る新規投稿フォーム</h1>

  <form action='{% url "bbs:create" %}' method="post">
    {% csrf_token %}<!-- セキュリティのための記述 -->
    {{ articleForm }}<!-- views.pyから受け取ったarticleFormを表示 -->
    <button type='submit'>投稿</button>
    <a href='{% url "bbs:index" %}'>一覧ページへ戻る</a>
  </form>
{% endblock %}

monju_project/templates/bbs/posted.html
{% extends "./base.html" %}
 
{% block content %}
    <h1>{{ article.id }}の投稿が完了しました！</h1>
    <p>{{ article.content }}, {{article.user_name }}</p>
    <p><a href='{% url "bbs:index" %}'>一覧ページへ戻る</a></p>
{% endblock %}